### ISSUE TITLE
Syntax error?

### ISSUE THREAD

**Issue by CDWimmer** [esmBot/esmBot#15]
After having some issues following the extremely sparse installation instructions I believe I've managed to set it up, however I'm now getting this hilariously useless error when I do ./app.js

```
root@scw-0f5137:~/esmbot/esmBot# ./app.js
./app.js: line 1: //: Is a directory
./app.js: line 2: syntax error near unexpected token `"dotenv"'
./app.js: line 2: `require("dotenv").config();'
```

I'm a discord.py user myself so I've no idea where to begin solving this. The file looks fine? First 2 lines: 
```
// load config from .env file
require("dotenv").config();
```

Any ideas?

**Comment by TheEssem** [comment]
What are the contents of your .env file?

**Comment by ToxicFrazzles** [comment]
A shebang line such as `#!/usr/bin/env node` could be added to the start of the file to facilitate running the file in this way. An alternative would be to specify how to run the file in the usage section of readme.md rather than just 
> run `app.js`
to make it clearer how to run it for people not familiar with node.

**Comment by TheEssem** [comment]
I've added a start script to the package.json, so you should be able to run `npm start` to run the bot now.
