### ISSUE TITLE
Image natives CPU pinning

### ISSUE THREAD

**Issue by TheEssem** [esmBot/esmBot#374]
Recently, an issue has popped up where the image natives seem to randomly take up an entire CPU core after certain operations. This can also stack with multiple operations, which can quickly become an issue in large-scale environments. I'm not quite sure if this is an issue with the bot or with libvips, however I'm putting it here because multiple people have reported this issue in the support/development chat (and I myself have experienced it).

The current cause of the issue is unknown. Interestingly, nearly every time a core is pinned, this is logged:
```
vips_image_dispose: temp-25 linear computed 126000%
vips_image_dispose: temp-19 relational_const computed 17400%
```
Do note, however, that this is also logged occasionally even without a core being pinned, so this may be unrelated. Still worth mentioning, however.

**Comment by dd-pardal** [comment]
After a few hours of `git bisect`ing and debugging, I have narrowed down the issue.

It turns out this is not related to the natives at all. In fact, I can reproduce the issue with only 3 files on aarch64 Debian (Raspberry Pi 4 Model B 2GB):

`package.json`:
```json
{"type":"module","dependencies":{"undici":"5.21.2"}}
```

`test.js`:
```js
import { Worker } from "worker_threads";
import path from "path";
import { fileURLToPath } from "url";

new Worker(path.join(path.dirname(fileURLToPath(import.meta.url)), "./test-worker.js"));
```

`test-worker.js`:
```js
import { request } from "undici";

request("https://media.tenor.com/qy_WcGdRzfgAAAAC/xluna-high-five.gif").then(res => res.body.arrayBuffer()).then(buf => Buffer.from(buf))
  .then(() => ({
    buffer: Buffer.alloc(10),
    fileExtension: "bin"
  }))
  .then(() => {
    process.exit();
  });
```

I believe this is caused by a bug in Node.js, but it might also be caused by undici.

---

Removing `undici.request()` from `utils/image-runner.js` fixes the issue for me. Removing `process.exit()` from `utils/image-runner.js`, allowing the worker to exit naturally when the event loop queue is empty, also fixes the issue for me. I made a pull request that does both things. Importing a library as big as undici when every image command is run (in the case of `API_TYPE=none`) probably slows down things a bit so removing it is a positive change, IMO.

**Comment by dd-pardal** [comment]
After a bit more testing, I'm pretty sure this is an issue with Node.js. I can't reproduce it after commenting out this part of the code, which should be undetectable by undici:

```js
  .then(() => (/*{
    buffer:*/ Buffer.alloc(10)/*,
    fileExtension: "bin"
  }*/))
```
