### ISSUE TITLE
Flag of Martinique is instead the flag of France

### ISSUE THREAD

**Issue by AshKmo** [esmBot/esmBot#379]
### Describe the bug

The flag command overlays the flag of France onto the image when the flag of Martinique is selected, as all of esmBot's images labelled "MQ" instead have the flag of France in them. Although I am running a self-hosted instance, a `git pull` revealed that my instance is fully up-to-date.

### Steps to reproduce

Run the flag command on an image with the flag set to :flag_mq:

### Expected behavior

The command should overlay the flag of Martinique onto the image

### Self-hosted instance?

Yes

**Comment by TheEssem** [comment]
This looks to be an upstream issue with the region-flags repo, where esmBot gets its flag images: https://github.com/fonttools/region-flags/blob/0f2ae1a950b35d406635cd5d0e3c1b1c837937c3/png/MQ.png

I did some research on the flag itself, and it does seem to be a topic of debate; technically the region-flags repo was correct as of 2022, since the "official" flag was just the flag of France for many centuries. However, there was an unofficial, yet controversial "snake flag" that nearly every emoji vendor uses instead, and you can see that flag being used on Discord. Martinique only got a proper official flag a few months ago, so technically the emojis are inaccurate as well.

I'll probably go ahead and fork the repo to add the "snake flag" since it lines up with the emoji vendor designs, but I'll also be making an issue on jdecked's Twemoji fork (the one that Discord uses) and possibly Noto Emoji about it.

**Comment by TheEssem** [comment]
Fixed in https://github.com/esmBot/region-flags/commit/7944a65a179be57c928f705541f8b7e42e2a44b7 and https://github.com/esmBot/esmBot/commit/6f607cfcf01d9d21ed023117165e59f58ce52d1f, should be able to `git pull` and `git submodule update`.
