### ISSUE TITLE
Error when executing command "&bruh"

### ISSUE THREAD

**Issue by Architect-Ent-DeveloperSide** [esmBot/esmBot#39]
An error was occured when a music bot was, ofc, playing music.

Error text file stated:

`Message: TypeError: Cannot read property 'host' of undefined

Stack Trace: TypeError: Cannot read property 'host' of undefined
    at Object.exports.play (/home/esmBot/esmBot/utils/soundplayer.js:58:49)
    at exports.run (/home/esmBot/esmBot/commands/bruh.js:4:28)
    at Client.module.exports (/home/esmBot/esmBot/events/messageCreate.js:72:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)`

**Comment by TheEssem** [comment]
Seems to be related to Lavalink disconnecting, there does seem to be an issue with it on the main bot (likely due to [Discord attempting to block Hetzner from accessing their voice servers](https://www.reddit.com/r/discordapp/comments/70dwa6/ip_banned_from_discord/dn2tuam/)) so I might have to move the Lavalink node(s) elsewhere

**Comment by TheEssem** [comment]
Although the server also seems to be unstable somewhat, I've managed to set up a Lavalink node on another server hosted by a friend. I also found another hosting provider which seems to give a much better deal than Hetzner (with the advantage of not being blocked by Discord's voice servers), so I might end up moving to that one and host a Lavalink node myself.
