### ISSUE TITLE
Gif becomes staticy and glitchy

### ISSUE THREAD

**Issue by AnnieStars** [esmBot/esmBot#412]
### Describe the bug

So, I'm trying to use /spin to make an image spin, but the result becomes a staticy and glitchy mess
It's never done this before and only started doing it recently, likely after the newest update

### Steps to reproduce

1. Type /spin
2. Select any image
3. Send
4. Gif becomes staticy and glitchy

### Expected behavior

It's supposed to be a clean spinning motion, but some colors become distorted and static

### Screenshots

Not screenshots, but gifs that showcase the expected result vs the bugged result

![spin-3](https://github.com/esmBot/esmBot/assets/87558827/bebe7a1e-1867-4812-b9da-8e27fdbcd4a2)
![spin-2](https://github.com/esmBot/esmBot/assets/87558827/d9984e0b-c03a-4055-a91f-5f038d812a17)

### Self-hosted instance?

No

### Additional context

It's only /spin, no other commands that turn images to gifs do this

**Comment by TheEssem** [comment]
Interesting; there haven't been any changes to that command between 1.10.2 and 1.10.3, so I'm thinking it's probably an upstream issue. The spin command is one of the few that hasn't been converted to libvips yet, so completing #290 should fix this due to the GIF handling in libvips being much higher quality.

**Comment by TheEssem** [comment]
This has been fixed with 0b45cba!
