### ISSUE TITLE
More Speech Bubble options

### ISSUE THREAD

**Issue by VillainsRule** [esmBot/esmBot#444]
### Describe the request

I really like the Speech Bubble feature, and I feel like more customization could be added. For example, an option where the bubble could be 2x shorter, or the speech bubbles could come from the bottom.

### Is your feature request related to a problem? Please describe.

I often have names omitted from larger speech bubble images, which is annoying. I need to mock people.

### Additional context

I love esmbot - thanks for making it!

**Comment by TheEssem** [comment]
The ability to put the speech bubble on the bottom has been implemented with 83ebe6ff0cb1ad7742aba6d9b7cafa8e67fffb07, but has yet to appear in a proper release; being able to manually scale the speech bubble is a good idea though and relatively easy to implement, so I've gone ahead and done that with 17c1b28161af0e0928bdcfc36786a15162be8447.

**Comment by TheEssem** [comment]
> Thanks! Is there a planned time for the next proper release?

I really wish I could give an approximate date, but unfortunately things have still been a bit rough here in the months since 1.10.3 was released. There have been multiple major changes to the bot since then, and tracking down potential remaining bugs resulting from all of them combined with having to manage other projects, deal with responsibilities IRL, and handle other issues of my own has made it difficult to find a proper time to release.

Things are starting to look up at least a little bit, and I hope to be able to release the next version relatively soon, but with the current state of things it will still probably be a difficult task. However, I intend to change the versioning scheme with this in mind, and once this version is released I feel that things will probably lighten up a bit and that I can start to publish releases more regularly afterwards.
